name: ▲ Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: loreddev/.github/.github/workflows/vercel-deploy.yml@main
    secrets: inherit
    with:
      production: true
